baselines:
  clip_based_reward: true
  clip_encoding_time: 15
  pixel_rendering_time: 7
  pretrained_locomotion: false
  random_policy: false
  vision_based_reward: false
environment:
  alternatives:
  - HalfCheetah-v4
  - Ant-v4
  - Walker2d-v4
  max_episode_steps: 1000
  name: Humanoid-v4
  render_mode: null
evaluation:
  benchmark_against_clip: true
  compute_similarity_metrics: true
  cross_evaluation: false
  eval_deterministic: true
  n_eval_episodes: 3
  reward_threshold_success: 100.0
  save_episode_videos: false
  similarity_threshold_excellent: 0.8
  similarity_threshold_good: 0.6
  track_computation_times: true
experiment:
  authors:
  - Yunus Emre Balci
  description: Enhanced motion-language control using direct MotionGPT integration
  institution: SDU
  name: direct_motion_language_learning
  version: '2.0'
experimental:
  adaptive_curriculum: false
  augmentation_noise_std: 0.01
  curriculum_success_threshold: 0.75
  use_audio_instructions: false
  use_instruction_specific_rewards: true
  use_motion_augmentation: false
  use_progress_bonus: true
  use_visual_features: false
hardware:
  compile_model: false
  device: auto
  gradient_accumulation_steps: 1
  max_memory_usage_gb: 8.0
  mixed_precision: false
hierarchical:
  discover_skills: false
  high_level_freq: 1
  low_level_freq: 10
  n_discovered_skills: 16
  skill_embedding_dim: 64
  use_hierarchical_structure: true
instructions:
  advanced:
  - walk in a circle
  - walk forward then turn left
  - walk backward then turn around
  - jump up and down
  - wave your hand while walking
  - crouch down low
  - walk sideways to the left
  - walk sideways to the right
  - run in a circle
  - march in place
  basic:
  - walk forward
  - walk backward
  - turn left
  - turn right
  - stop moving
  expert:
  - walk forward slowly then speed up
  - turn left then walk backward
  - jump three times then walk forward
  - wave both hands while walking forward
  - walk in a figure eight pattern
  - crouch walk forward
  - walk forward then jump then continue walking
  intermediate:
  - walk forward slowly
  - walk forward quickly
  - run forward
  - turn left while walking
  - turn right while walking
  - walk in place
logging:
  log_level: INFO
  save_model_every_n_steps: 10000
  tensorboard_log: ./logs/
  track_metrics:
  - motion_language_similarity
  - language_reward
  - original_env_reward
  - episode_length
  - computation_time
  - motion_variance
  wandb_project: null
motion_gpt:
  checkpoint_path: null
  codebook_size: 512
  config_path: null
  language_model: t5-small
  latent_dim: 256
  max_sequence_length: 196
  motion_dim: 263
  motion_history_length: 20
  motion_normalization: true
  reward_smoothing: 0.9
  success_threshold: 0.6
  temporal_aggregation: weighted_recent
reproducibility:
  deterministic_training: false
  generate_performance_plots: true
  save_hyperparameters: true
  save_model_architecture: true
  save_random_state: true
  save_training_curves: true
  seed: 42
training:
  batch_size: 64
  checkpoint_freq: 5000
  clip_range: 0.2
  ent_coef: 0.01
  eval_freq: 10000
  gae_lambda: 0.95
  gamma: 0.99
  language_reward_weights:
  - 0.3
  - 0.4
  - 0.5
  - 0.6
  - 0.7
  - 0.8
  - 0.9
  learning_rate: 3e-4
  max_grad_norm: 0.5
  n_epochs: 10
  n_parallel_envs: 2
  n_steps: 2048
  total_timesteps_per_instruction: 10000
  use_multiprocessing: false
  vf_coef: 0.5
